from app.entity.custom_algorithm import CustomAlgorithm
from app.entity.doc import Doc
from app.entity.doc_relation import DocRelation
from app.entity.doc_term import DocTerm
from app.entity.doc_type import DocType
from app.entity.evaluate_task import EvaluateTask
from app.entity.export_job import ExportJob
from app.entity.mark_job import MarkJob
from app.entity.mark_task import MarkTask
from app.entity.nlp_task import NlpTask
from app.entity.predict_job import PredictJob
from app.entity.predict_task import PredictTask
from app.entity.relation_m2m_term import RelationM2mTerm
from app.entity.status import Status
from app.entity.train_job import TrainJob
from app.entity.train_m2m_mark import TrainM2mMark
from app.entity.train_task import TrainTask
from app.entity.train_term_task import TrainTermTask
from app.entity.user_task import UserTask
